### ISSUE TITLE
IS 10.5 image build missing e2ei/11/MFC_19.10.0.0.LATEST/MFC/MfcAll 

### ISSUE THREAD

**Issue by Myhael76** [SoftwareAG/sag-unattended-installations#4]
Automatic image building of IS 10.5 reported a missing product (e2ei/11/MFC_19.10.0.0.LATEST/MFC/MfcAll), which makes the test fail.

Product image builder should report missing products in an explicit report.

**Comment by miunsag** [comment]
MFC is required on Windows, but all this repo is thought for Linux. The template contained the wrong reference.

**Comment by miunsag** [comment]
Closing - we don't use POSIX scripts for Windows installations

**Comment by miunsag** [comment]
Closing - we don't use POSIX scripts for Windows installations
